export const PUBLIC_REQUESTS = {
  LOGIN: 'login',
  REGISTRATION_STUDENT: 'registration/student',
  REGISTRATION_TEACHER: 'registration/teacher',
  REGISTRATION_COMPANY: 'registration/company',
  IS_AUTH: 'is-auth',
  GET_SUBJECTS: 'subjects',
  GET_TEACHERS: 'teachers',
  GET_TEACHER_PROFILE: 'teacher-profile',
}

export const PRIVATE_REQUESTS = {
  USER_INFO: 'user-info',
  USER_DELETE: 'delete',
  UPDATE_PASSWORD: 'update-password',
  ADD_SUBJECT_STUDENT: 'add-subject/student',
  REMOVE_SUBJECT_STUDENT: 'remove-subject/student',
  GET_SUBJECTS_STUDENT: 'get-subjects/student',
  MAIN_FIELDS_ACTIVITY: 'main-fields-activity',
  PERSONAL_INFO: 'personal-info',
  PERSONAL_LESSONS_TEACHER: 'personal-lessons/teacher',
  WORK_EXPERIENCE: 'work-experience',
  PAYMENT_CARD: 'payment-card',
  UPLOAD_AVATAR: 'upload-avatar',
  UPLOAD_VIDEO: 'upload-video',
  UPLOAD_CERTIFICATE: 'upload-certificate',
  CREATE_LESSON: 'create-lesson',
  UPDATE_LESSON: 'update-lesson',
  DELETE_LESSON: 'delete-lesson',
  GET_LESSON: 'get-lesson',
  GET_LESSONS: 'get-lessons',
  CREATE_LESSON_MODULE: 'create-lesson-module',
  UPDATE_LESSON_MODULE: 'update-lesson-module',
  DELETE_LESSON_MODULE: 'delete-lesson-module',
  GET_LESSON_MODULE: 'get-lesson-module',
  GET_MODULES_LESSON: 'get-modules-lesson',
  GET_STUDENTS: 'get-students',
  ADD_STUDENT_TO_LESSON: 'add-student-to-lesson',
  DELETE_STUDENT_FROM_LESSON: 'delete-student-from-lesson',
  GET_STUDENTS_FROM_LESSON: 'get-students-from-lesson',
}
